openapi: 3.0.0
info:
  title: Order API
  version: '1.0'
  description: Order Processing Services for supported payment methods
  contact:
    email: grablink.engineering@grab.com
    name: GrabLink Engineering
servers:
  - url: localhost
paths:
  /order:
    post:
      summary: Create Order
      operationId: post-order
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  order_id:
                    type: string
                  merchant_order_num:
                    type: string
                  order_status:
                    type: string
                  payer:
                    type: object
                    properties:
                      reference_id:
                        type: string
                  cart:
                    type: object
                    properties:
                      cart_currency:
                        type: string
                      cart_total:
                        type: string
                  hpp:
                    type: object
                    properties:
                      redirect_url:
                        type: string
                  metadata:
                    type: string
              examples: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                merchant_order_num:
                  type: string
                capture_after_hours:
                  type: string
                route_indicator:
                  type: string
                require_3ds:
                  type: boolean
                payer:
                  type: object
                  required:
                    - reference_id
                  properties:
                    reference_id:
                      type: string
                      description: Unique customer identifier.
                    name:
                      type: string
                    email:
                      type: string
                    phone:
                      type: string
                    billing_address:
                      type: object
                      properties:
                        city:
                          type: string
                        country:
                          type: string
                        state:
                          type: string
                        building_name:
                          type: string
                        street:
                          type: string
                        postal_code:
                          type: string
                    shipping_address:
                      type: object
                      properties:
                        city:
                          type: string
                        country:
                          type: string
                        state:
                          type: string
                        building_name:
                          type: string
                        street:
                          type: string
                        postal_code:
                          type: string
                statement_descriptor:
                  type: string
                cart:
                  type: object
                  properties:
                    cart_currency:
                      type: string
                    cart_total:
                      type: string
                    cart_subtotal:
                      type: string
                    cart_discount:
                      type: string
                    cart_tax:
                      type: string
                    cart_shipping_fee:
                      type: string
                    cart_admin_fee:
                      type: string
                    cart_items:
                      type: array
                      items:
                        type: object
                        properties:
                          item_name:
                            type: string
                          item_quantity:
                            type: number
                          item_price:
                            type: string
                          item_image:
                            type: string
                          item_option:
                            type: string
                hpp:
                  type: object
                  properties:
                    return_url:
                      type: string
                    cancel_url:
                      type: string
                    browser_info:
                      type: object
                      properties:
                        user_agent:
                          type: string
                        ip:
                          type: string
                metadata:
                  type: string
              required:
                - payer
            examples: {}
        description: Create Order
      description: Create Order
      parameters:
        - schema:
            type: string
            description: application/json
          in: header
          name: Content-Type
          required: true
        - schema:
            type: string
            description: HMAC-SHA512
          in: header
          name: Signature
          required: true
        - schema:
            type: string
            description: UNIX Timestamp
          in: header
          name: Timestamp
          required: true
        - schema:
            type: string
            format: uuid
          in: header
          name: X-Request-ID
      tags:
        - Order
      security:
        - API Key: []
    parameters: []
  '/order/{order_id}':
    parameters:
      - schema:
          type: string
        name: order_id
        in: path
        required: true
    get:
      summary: Retrieve Order
      tags:
        - Order
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  order_id:
                    type: string
                  merchant_order_num:
                    type: string
                  order_status:
                    type: string
                  payer:
                    type: object
                    properties:
                      reference_id:
                        type: string
                  cart:
                    type: object
                    properties:
                      cart_currency:
                        type: string
                      cart_total:
                        type: string
                  transaction:
                    type: object
                    properties:
                      trans_id:
                        type: string
                      action_time:
                        type: string
                      merchant_action_id:
                        type: string
                      trans_amount:
                        type: object
                        properties:
                          currency:
                            type: string
                          value:
                            type: string
                      result:
                        type: object
                        properties:
                          code:
                            type: string
                          message:
                            type: string
                          raw_message:
                            type: string
                      auth_code:
                        type: string
                      cvc_result:
                        type: string
                      avs_result:
                        type: string
                      acquirer_reference:
                        type: string
                      payer:
                        type: object
                        properties:
                          reference_id:
                            type: string
                        required:
                          - reference_id
                      payment_method:
                        type: object
                        properties:
                          card:
                            type: object
                            properties:
                              brand:
                                type: string
                              first_6:
                                type: string
                              last_4:
                                type: string
                              funding_type:
                                type: string
                              category:
                                type: string
                              issuing_country:
                                type: string
                              issuing_bank:
                                type: string
                          token:
                            type: object
                            properties:
                              token_id:
                                type: string
                          fingerprint:
                            type: string
                      trans_status:
                        type: string
                  metadata:
                    type: string
              examples: {}
      operationId: get-order-order_id
      description: Retrieve Order
      security:
        - API Key: []
  '/order/{order_id}/cancel':
    parameters:
      - schema:
          type: string
        name: order_id
        in: path
        required: true
    post:
      summary: Cancel Order
      operationId: post-order-order_id-cancel
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  merchant_order_num:
                    type: string
                  order_status:
                    type: string
                  payer:
                    type: object
                    properties:
                      reference_id:
                        type: string
                  cart:
                    type: object
                    properties:
                      cart_currency:
                        type: string
                      cart_total:
                        type: string
              examples: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                initiating_reason:
                  type: string
            examples: {}
      description: Cancel Order
      parameters:
        - schema:
            type: string
            description: application/json
          in: header
          name: Content-Type
          required: true
        - schema:
            type: string
            description: HMAC-SHA512
          in: header
          name: Signature
          required: true
        - schema:
            type: string
            description: UNIX Timestamp
          in: header
          name: Timestamp
          required: true
        - schema:
            type: string
            format: uuid
          in: header
          name: X-Request-ID
      tags:
        - Order
      security:
        - API Key: []
components:
  schemas: {}
  securitySchemes:
    API Key:
      name: X-Api-Key
      type: apiKey
      in: header
tags:
  - name: Order
