openapi: 3.0.0
info:
  title: Payment Method API
  version: '1.0'
  description: Tokenization Services for supported payment methods
  contact:
    email: grablink.engineering@grab.com
    name: GrabLink Engineering
servers:
  - url: localhost
paths:
  /payment_method:
    post:
      summary: Add Payment Method
      operationId: post-payment-method
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  action_time:
                    type: string
                  merchant_action_id:
                    type: string
                  result:
                    type: object
                    required:
                      - code
                      - message
                    properties:
                      code:
                        type: string
                      message:
                        type: string
                      raw_message:
                        type: string
                  three_ds:
                    type: object
                    properties:
                      redirection_url:
                        type: string
                  payer:
                    type: object
                    required:
                      - reference_id
                    properties:
                      reference_id:
                        type: string
                  payment_method:
                    type: object
                    properties:
                      card:
                        type: object
                        properties:
                          brand:
                            type: string
                          first_6:
                            type: string
                          last_4:
                            type: string
                          funding_type:
                            type: string
                          category:
                            type: string
                          issuing_country:
                            type: string
                          issuing_bank:
                            type: string
                      token:
                        type: object
                        properties:
                          token_id:
                            type: string
                      fingerprint:
                        type: string
                  metadata:
                    type: string
                required:
                  - merchant_action_id
                  - result
                  - payer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                merchant_action_id:
                  type: string
                  description: Unique transaction identifier.
                route_indicator:
                  type: string
                require_3ds:
                  type: string
                three_ds:
                  type: object
                  properties:
                    return_url:
                      type: string
                    browser_info:
                      type: object
                      properties:
                        accept_header:
                          type: string
                        user_agent:
                          type: string
                three_ds_data:
                  type: object
                  properties:
                    xid:
                      type: string
                    status:
                      type: string
                    eci:
                      type: string
                    auth_value:
                      type: string
                    auth_algo:
                      type: string
                payer:
                  type: object
                  required:
                    - reference_id
                  properties:
                    reference_id:
                      type: string
                      description: Unique customer identifier.
                    name:
                      type: string
                    email:
                      type: string
                    phone:
                      type: string
                    billing_address:
                      type: object
                      properties:
                        city:
                          type: string
                        country:
                          type: string
                        state:
                          type: string
                        building_name:
                          type: string
                        street:
                          type: string
                        postal_code:
                          type: string
                    shipping_address:
                      type: object
                      properties:
                        city:
                          type: string
                        country:
                          type: string
                        state:
                          type: string
                        building_name:
                          type: string
                        street:
                          type: string
                        postal_code:
                          type: string
                payment_method:
                  type: object
                  properties:
                    card:
                      type: object
                      properties:
                        number:
                          type: string
                        expiry_month:
                          type: string
                        expiry_year:
                          type: string
                        cvc:
                          type: string
                        holder_name:
                          type: string
                metadata:
                  type: string
              required:
                - merchant_action_id
                - payer
                - payment_method
        description: Add Payment Method
      description: Add Payment Method
      parameters:
        - schema:
            type: string
            description: application/json
          in: header
          name: Content-Type
          required: true
        - schema:
            type: string
            description: HMAC-SHA512
          in: header
          name: Signature
          required: true
        - schema:
            type: string
            description: UNIX Timestamp
          in: header
          name: Timestamp
          required: true
        - schema:
            type: string
            format: uuid
          in: header
          name: X-Request-ID
      tags:
        - Payment Method
      security:
        - API Key: []
  '/payment_method/{token_id}':
    parameters:
      - schema:
          type: string
        name: token_id
        in: path
        required: true
        description: Token ID
    get:
      summary: Retrieve Payment Method
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  action_time:
                    type: string
                  merchant_action_id:
                    type: string
                  result:
                    type: object
                    required:
                      - code
                      - message
                    properties:
                      code:
                        type: string
                      message:
                        type: string
                      raw_message:
                        type: string
                  payer:
                    type: object
                    required:
                      - reference_id
                    properties:
                      reference_id:
                        type: string
                  payment_method:
                    type: object
                    properties:
                      card:
                        type: object
                        properties:
                          brand:
                            type: string
                          first_6:
                            type: string
                          last_4:
                            type: string
                          funding_type:
                            type: string
                          category:
                            type: string
                          issuing_country:
                            type: string
                          issuing_bank:
                            type: string
                      token:
                        type: object
                        properties:
                          token_id:
                            type: string
                      fingerprint:
                        type: string
                  metadata:
                    type: string
                required:
                  - result
                  - payer
      operationId: get-payment-method-id
      parameters:
        - schema:
            type: string
            format: uuid
          in: header
          name: X-Request-ID
      description: Retrieve Payment Method
      tags:
        - Payment Method
      security:
        - API Key: []
    delete:
      summary: Delete Payment Method
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  action_time:
                    type: string
                  merchant_action_id:
                    type: string
                  result:
                    type: object
                    required:
                      - code
                      - message
                    properties:
                      code:
                        type: string
                      message:
                        type: string
                      raw_message:
                        type: string
                  payer:
                    type: object
                    required:
                      - reference_id
                    properties:
                      reference_id:
                        type: string
                  payment_method:
                    type: object
                    properties:
                      card:
                        type: object
                        properties:
                          brand:
                            type: string
                          first_6:
                            type: string
                          last_4:
                            type: string
                          funding_type:
                            type: string
                          category:
                            type: string
                          issuing_country:
                            type: string
                          issuing_bank:
                            type: string
                      token:
                        type: object
                        properties:
                          token_id:
                            type: string
                      fingerprint:
                        type: string
                  metadata:
                    type: string
                required:
                  - result
                  - payer
      operationId: delete-payment-method-id
      parameters:
        - schema:
            type: string
          in: header
          name: Content-Type
        - schema:
            type: string
          in: header
          name: Signature
        - schema:
            type: string
          in: header
          name: Timestamp
        - schema:
            type: string
            format: uuid
          in: header
          name: X-Request-ID
      description: Delete Payment Method
      tags:
        - Payment Method
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                merchant_action_id:
                  type: string
            examples:
              Example:
                value:
                  webhook: string
        description: Delete Payment Method
      security:
        - API Key: []
components:
  schemas: {}
  securitySchemes:
    API Key:
      name: X-Api-Key
      type: apiKey
      in: header
tags:
  - name: Payment Method
